language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install -r tests/requirements.txt
  - pip install .

# command to run tests
script:
  - black --check .
  - pylint -v mlsploit
  - coverage run -m pytest -vv

after_success:
  - codecov # submit coverage
